rules:
  spellcheck-tech-word: true
  preset-smarthr:
    ja-space-between-half-and-full-width:
      space: always

filters:
  allowlist:
    allow:
      # https://zenn.dev/zenn/articles/markdown-guide#%E3%82%A2%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E3%83%B3%EF%BC%88%E3%83%88%E3%82%B0%E3%83%AB%EF%BC%89
      - /:+details\s+.+/
      - /:::message\s+.+/
